### ISSUE TITLE
SC Monitoring Instance or Endpoint?

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/ServiceControl.Monitoring#108]
Documentation talks about SC [**Monitoring Instance**](https://docs.particular.net/servicecontrol/monitoring-instances/), but installer says "endpoint".

![image](https://user-images.githubusercontent.com/1309622/35302587-44d518e2-004c-11e8-85f2-d08ea364f74d.png)

Should it be renamed?

**Comment by mikeminutillo** [comment]
Yes. It should say instance. I will update it.
