### ISSUE TITLE
Default Port number

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl.Monitoring#14]
Can we change the default port from 1234 to something else?  This is a pretty common choice for custom services so there is a high likelihood of a clash.   @mikeminutillo  had one when he first started looking at this project

**Comment by Scooletz** [comment]
Which number should that be? High enough, greater than 10000?

**Comment by gbiellem** [comment]
There's no right answer to what should it be :)

How about something similar to SC's 33333.  Perhaps 33633?

**Comment by mikeminutillo** [comment]
Should there be a default? What does the SCMU do if you create a new
instance and 33333 is taken? Does it automatically change it to 33334?
Should we use the same process for the Monitoring component?

**Comment by gbiellem** [comment]
When I raised this I wasn't thinking about SCMU,  just the debugging experience. It would be annoying to have to kill another service otr change the port every time you want to work on it

Regarding SCMU t has some validation to ensure no instances are set up on the same port
As for clashing with other app I don't think it checks the port number until after you submit.  @DavidBoike  raised an issue to change this https://github.com/Particular/ServiceControl/issues/895

>  Does it automatically change it to 33334?

If the default is taken we leave it blank and validation prompts the user to supply the port on submit

**Comment by DavidBoike** [comment]
I really like how the Raven installer handles it:

![](https://ravendb.net/RavenFS/GetImage?filePath=/docs/3.5/installer_windows_service.png)

**Comment by gbiellem** [comment]
I added a similar check to SCMU branch we are working on. It'll now throw a
validation error if the port you specified is already in use

**Comment by tmasternak** [comment]
The default port has been chosen to be `33633` it's configuration and validation is handled in SCMU the same way as SC port.
