### ISSUE TITLE
Decide how SP knows about the monitoring endpoint

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl.Monitoring#15]
related to https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/51

@SzymonPobiega has there been a discussion on how SP discovers the URL for the monitoring?

 Will this be a manual config setting in SP? or is SC supposed to know about it and forward on the URL info.  Need to know so we can implement any required setting changes into SCMU or SC.

//cc @mikeminutillo

**Comment by SzymonPobiega** [comment]
@gbiellem I don't recall any discussions. I think some people (including me) assumed that the monitoring URL will be configured when installing SP. 

If we want to forward/redirect then it should be probably monitoring redirecting to SC, not vice versa because the monitoring part will have higher availability requirements.

**Comment by gbiellem** [comment]
> I think some people (including me) assumed that the monitoring URL will be configured when installing SP.

Not @mikeminutillo  - He outlined the idea of having SC provide the the monitoring URL to SP to me which is why I asked.  

@mikeminutillo  care to chime in?

**Comment by WilliamBZA** [comment]
Simplest possible thing is to have a manual config screen in SP as a version 1. Auto discovery/provisioning/configuration can be vNext upgrades.

**Comment by gbiellem** [comment]
@WilliamBZA  By "SP" you mean the SP MSI installation, so same way as we config SC URL. Correct?

**Comment by WilliamBZA** [comment]
@gbiellem Correct. We don't have any way to edit the settings file from within the SP web ui, so if we wanted to expose the config there we'd have to first overcome that technical hurdle whereas the installer has that problem solved for us.

**Comment by gbiellem** [comment]
Yeah that's what I thought

**Comment by mikeminutillo** [comment]
I think the best idea for now is to just add another config url. It means
we can continue to run the monitoring experience while SC is offline. I
like the idea of auto-discovery and config but it can wait.

I can only think of two cons:
- Users might get these the wrong way around.
- Users can now configure SP to point to two different environments at once.

**Comment by tmasternak** [comment]
The end decision was to add additional configuration parameter. The value provided in the SP installer is validated by pinging the specified endpoint to check it's existence.
