### ISSUE TITLE
Remove reliance on custom build task

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl.Monitoring#208]
The [Packaging project](https://github.com/Particular/ServiceControl.Monitoring/blob/develop/src/Packaging.ServiceControl.Monitoring/Packaging.ServiceControl.Monitoring.csproj) was ported over from the way we do in ServiceControl which was [just updated to use a standard `ZipDirectory` MSBuild task](https://github.com/Particular/ServiceControl/pull/1646). We should follow suit and make a similar change here. This allows us to remove the dependency on the custom `AddToZip` build task.

**Comment by tmasternak** [comment]
This was done as part of the migration to the ServiceControl repository.
