### ISSUE TITLE
RawDataProvider should handle out-of-order messages

### ISSUE THREAD

**Issue by tmasternak** [Particular/ServiceControl.Monitoring#23]
Currently if the messages get delivered out-of-order for a given endpoint (which is not unlikely) the current value for metrics will be not the most recent but the [last processed](https://github.com/Particular/ServiceControl.Monitoring/blob/develop/src/ServiceControl.Monitoring/Raw/RawDataProvider.cs#L21).

**Comment by Scooletz** [comment]
This is solely the delivery aspect, right?. The processing is pretty straight forward and much unlikely to result in this behavior.

**Comment by mikeminutillo** [comment]
@tmasternak is this still relevant?

**Comment by tmasternak** [comment]
no it is not
