### ISSUE TITLE
Better data structures for queue length

### ISSUE THREAD

**Issue by Scooletz** [Particular/ServiceControl.Monitoring#35]
_This issue summarizes a few potential improvements that can ensure a good stable performance of the queue length reporting._

The current approach faces following challenges:
- [QueueLengthCalculator](https://github.com/Particular/ServiceControl.Monitoring/blob/3714b7f056386f614dbad20e5801a810233dc134/src/ServiceControl.Monitoring/QueueLength/QueueLengthDataStore.cs)
  - whenever queue lengths are obtained, the cleaning procedure is called for data points, that are no longer withing the historical period ([this line](https://github.com/Particular/ServiceControl.Monitoring/blob/3714b7f056386f614dbad20e5801a810233dc134/src/ServiceControl.Monitoring/QueueLength/QueueLengthDataStore.cs#L36))
  - whenever an endpoint reports its sequences' values, endpoints are selected, that use same session numbers. In a following step, a snapshot is taken ([this line](https://github.com/Particular/ServiceControl.Monitoring/blob/3714b7f056386f614dbad20e5801a810233dc134/src/ServiceControl.Monitoring/QueueLength/QueueLengthDataStore.cs#L61)). This effectively means, that for every report, all the "connected" endpoints will have their data snapshotted
  - recalculation of the data is performed for all the endpoints and then, a single value, for a specific endpoint, is selected ([this line](https://github.com/Particular/ServiceControl.Monitoring/blob/3714b7f056386f614dbad20e5801a810233dc134/src/ServiceControl.Monitoring/QueueLength/QueueLengthDataStore.cs#L90)). This could be done in a more efficient manner if recalculations would be done only for a specific endpoint. It's easy to imagine running an endpoint publishing an event that is received by 4 other endpoints, then every of them being updated while still calculations are performed for each of them 4 times.

### Possible solution

If we split the recording part, from the reporting part we could use a following approach:
- whenever endpoint reports its sequences, it stores its sends and receives as in [here](https://github.com/Particular/ServiceControl.Monitoring/blob/3714b7f056386f614dbad20e5801a810233dc134/src/ServiceControl.Monitoring/QueueLength/QueueLengthDataStore.cs#L49) but without snapshotting and calculating which endpoint should be updated
- a background task is used to periodically snapshot all the endpoints, simply by calculating the queue lengths [like it's done now](https://github.com/Particular/ServiceControl.Monitoring/blob/3714b7f056386f614dbad20e5801a810233dc134/src/ServiceControl.Monitoring/QueueLength/QueueLengthDataStore.cs#L90)
- the storage for snapshots is changed from a `ConcurrentDictionary` that requires clean ups to a circullar buffer. With one task doing snapshots, there's a single writer, that can easily move forward for every snapshot, write it's date and data and use a bounded array of results as a circular buffer
- querying for data, done by [GetQueueLengths](https://github.com/Particular/ServiceControl.Monitoring/blob/3714b7f056386f614dbad20e5801a810233dc134/src/ServiceControl.Monitoring/QueueLength/QueueLengthDataStore.cs#L16), would change to calculating the offset of `now` in a circular buffer, and `Volatile.Read` its values (checking if the stored date is around now). 

With the following we get a simple and efficient storage that is bound, concurrent friendly and efficient both in terms of space and computation.

A separate thing is to properly remove sessions that are no longer needed.

**Comment by tmasternak** [comment]
@Scooletz can close this one? The estimated queue length has been replaced by the native one.
